#!/usr/bin/env bash

(
cd /home/ubuntu/kanban-prod
export DJANGO_SETTINGS_MODULE=kanban.settings.prod
export ENVIRONMENT=prod
/home/ubuntu/.virtualenvs/kanban/bin/python manage.py close_past_events

export PGUSER=ttcentral
export PGHOST=localhost
export PGPASSFILE=/home/ubuntu/.pgpass

TIMESTAMP=`date +"%Y-%m-%d_%H-%M-%S"`
PROD_DB=kanban_prod
DUMP=/home/ubuntu/db/$TIMESTAMP.$PROD_DB.dump.sql

pg_dump -f $DUMP $PROD_DB

export AWS_CONFIG_FILE=/home/ubuntu/.aws/config
export AWS_SHARED_CREDENTIALS_FILE=/home/ubuntu/.aws/credentials
aws s3 cp $DUMP s3://dbbackup.ttcentral.com/
) > /var/log/ttcentral/prod/daily_cron.log 2>&1
