#!/usr/bin/env bash

(
cd /home/ubuntu/kanban-staging
export DJANGO_SETTINGS_MODULE=kanban.settings.staging
export ENVIRONMENT=staging
/home/ubuntu/.virtualenvs/staging/bin/python manage.py event_management

) >> /var/log/ttcentral/staging/event_management.log 2>&1
